<a href="https://colab.research.google.com/github/TTrogdon22/Data-Science-/blob/main/TrogdonLab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Loops

In [1]:
for i in range(10):
     print(i)

0
1
2
3
4
5
6
7
8
9


In [2]:
for i in range(5,8):
    print(i)

5
6
7


In [3]:
for i in range(3):
     print("Test Number: ",i)

Test Number:  0
Test Number:  1
Test Number:  2


#Functions

In [4]:
def square(x):
    return x**2

In [5]:
square(5)

25

In [6]:
square(9)

81

In [7]:
square(square(2))

16

In [12]:
def add_two(x):
     return x+2

In [13]:
add_two(5)

7

#Logical Branching

In [42]:
choice = "apple"

In [46]:
if choice == "apple":

    print("You choose apples.")

else:

    print("You did not choose apples.")

You did not choose apples.


In [61]:
choice = "oranges"

In [62]:
if choice == "apple":

    print("You choose apples.")

else:

    print("You did not choose apples.")

You did not choose apples.


In [65]:
if choice == "apple":

    print("You choose apples.")
    print("Thank you, shop again!")
elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!")
else: 

    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

You did not choose apples or oranges.
Thank you, shop again!


In [111]:
choice = input("Please enter your choice (i.e. apple: ")

Please enter your choice (i.e. apple: pear


In [112]:
choice

'pear'

#Random Number Generator

In [67]:
import numpy as np
import matplotlib.pyplot as plt

In [92]:
np.random.permutation(52)

array([27, 32,  4,  7, 44, 50, 17, 47, 22, 41, 28,  2, 42, 16, 34, 24, 29,
       12, 36,  0,  5, 13, 39, 51, 30, 20, 45, 14, 35,  3, 43, 21, 11, 38,
       49, 37,  8, 48, 10, 18, 33, 26,  6, 19,  9,  1, 25, 40, 15, 31, 46,
       23])

In [99]:
cards= np.random.permutation(52)

In [100]:
cards

array([13,  3, 30,  1, 19, 28, 45, 46, 23, 50, 44, 18, 42, 51, 39, 33,  7,
       38, 32, 26, 31, 47, 17,  5, 11,  4,  8, 10, 24, 37,  0, 21, 35, 48,
       27, 12, 25, 36, 22,  2, 40, 34, 49, 20, 43, 15, 14,  9, 16, 41, 29,
        6])

In [101]:
cards[0]

13

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [105]:
np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [106]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [107]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [108]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [113]:
suits

['Clubs', 'Spades', 'Hearts', 'Diamonds']

In [114]:
suits[0]

'Clubs'

In [115]:
names[2]

'Three'

In [126]:
def card_name(card_number):
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [127]:
card_name(37)

'Queen of Hearts'

In [128]:
card_name(7)

'Eight of Clubs'

In [129]:
card_name(27)

'Two of Hearts'

In [163]:
cards = np.random.permutation(52)

In [164]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [158]:
top_of_deck, second_card_in_deck, last_card_in_deck

('Seven of Spades', 'Two of Diamonds', 'Queen of Spades')

In [165]:
for i in range(15):
    print(card_name(cards[i]))

Four of Clubs
Ace of Hearts
Three of Hearts
Seven of Clubs
Three of Clubs
Jack of Diamonds
Jack of Clubs
Four of Hearts
Eight of Diamonds
Ace of Diamonds
King of Clubs
Jack of Spades
Five of Hearts
King of Hearts
Queen of Diamonds


In [166]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [177]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [191]:
i = np.random.randint(4)
j = np.random.randint(13)

In [192]:
i,j

(2, 8)

In [193]:
suit[i]

's'

In [194]:
card[j]

'9'

In [205]:
from IPython.core.display import display, HTML

In [202]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [203]:
img = card_url_head + suit[i]+card[j] + card_url_tail

In [208]:
show_img(img)

In [209]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [210]:
card_image(3)

'k4'

In [211]:
img = card_url_head + card_image(3) + card_url_tail

In [212]:
show_img(img)

In [213]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)